(function(root){
'use strict';
const names={'uid-text':'Chữ ID',background:'Ảnh nền + UID','noi-bat':'Nhân vật nổi bật',sung:'Súng',accessories:'Xe + Linh tinh','nhan-vat':'Nhân vật thường',do:'Đồ nhỏ'},EPS=1e-6;
function clampRect(r,w,h){const rw=Math.min(w,Math.max(1,Number(r.w)||1)),rh=Math.min(h,Math.max(1,Number(r.h)||1));return {x:Math.max(0,Math.min(w-rw,Number(r.x)||0)),y:Math.max(0,Math.min(h-rh,Number(r.y)||0)),w:rw,h:rh};}
function overlaps(a,b){return Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)>EPS&&Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y)>EPS;}
function validLayout(rects){return rects.every((a,i)=>rects.slice(i+1).every(b=>!overlaps(a,b)));}
function bounds(rects){if(!rects.length)return null;const x=Math.min(...rects.map(r=>r.x)),y=Math.min(...rects.map(r=>r.y));return {x,y,w:Math.max(...rects.map(r=>r.x+r.w))-x,h:Math.max(...rects.map(r=>r.y+r.h))-y};}
// Find the first contact along the entire movement/resize, including large pointer jumps.
function contact(a,b,o){let low=0,high=1;const inequalities=[[a.x+a.w-o.x,b.x+b.w-a.x-a.w],[o.x+o.w-a.x,a.x-b.x],[a.y+a.h-o.y,b.y+b.h-a.y-a.h],[o.y+o.h-a.y,a.y-b.y]];for(const [v,d]of inequalities){if(Math.abs(d)<1e-12){if(v<=EPS)return 1;continue;}const t=(EPS-v)/d;if(d>0)low=Math.max(low,t);else high=Math.min(high,t);}return high-low>1e-9&&high>0&&low<1?Math.max(0,low):1;}
function constrain(start,end,others){let t=1;for(let i=0;i<start.length;i++)for(const o of others)t=Math.min(t,contact(start[i],end[i],o));if(t<1)t=Math.max(0,t-1e-8);return {t,limited:t<1,rects:start.map((a,i)=>Object.fromEntries(['x','y','w','h'].map(k=>[k,a[k]+(end[i][k]-a[k])*t])))};}
function create(paint,postprocess){
 const solids=list=>list.filter(l=>!l.overlay).map(l=>l.rect);
 const el=id=>document.getElementById(id),canvas=el('totalCanvas'),stage=el('totalStage'),viewport=el('totalViewport'),surface=el('totalSurface'),outline=el('layerOutline'),marquee=el('selectionMarquee');
 let layers=[],selected=new Set(),overrides=new Map(),base=null,customSize=null,zoom=1,zoomManual=false,drag=null,tool='move';
 const chosen=()=>layers.filter(l=>selected.has(l.id));
 const selectedBounds=()=>bounds(chosen().map(l=>l.rect));
 function save(l){overrides.set(l.id,{x:l.rect.x/canvas.width,y:l.rect.y/canvas.height,w:l.rect.w/canvas.width,h:l.rect.h/canvas.height});}
 function hint(text){el('editorHint').textContent=text;}
 function fields(){const list=chosen(),r=selectedBounds();outline.hidden=!r;el('selectionCount').textContent=list.length?list.length+' khối đang chọn':'Chưa chọn khối';el('blockSelect').value=list.length===1?list[0].id:'';el('selectedBoxes').replaceChildren();if(!r)return;if(list.length===1&&list[0].uidText){const fontInput=el('uidFontSize');if(document.activeElement!==fontInput)fontInput.value=Math.round(r.h*.70);}for(const [id,k]of [['blockX','x'],['blockY','y'],['blockW','w'],['blockH','h']])el(id).value=Math.round(r[k]);outline.style.left=r.x*zoom+'px';outline.style.top=r.y*zoom+'px';outline.style.width=r.w*zoom+'px';outline.style.height=r.h*zoom+'px';const boxes=el('selectedBoxes');boxes.replaceChildren();for(const l of list){const box=document.createElement('div');box.className='selected-box';Object.assign(box.style,{left:l.rect.x*zoom+'px',top:l.rect.y*zoom+'px',width:l.rect.w*zoom+'px',height:l.rect.h*zoom+'px'});boxes.append(box);}}
 function available(){return Math.max(100,el('totalEditor').clientWidth||viewport.parentElement?.clientWidth||1100);}
 function maxHeight(){return Math.max(300,Math.round((root.innerHeight||900)*.78));}
 function layout(){const w=canvas.width*zoom,h=canvas.height*zoom;viewport.style.width=available()+'px';viewport.style.height=maxHeight()+'px';canvas.style.width=w+'px';canvas.style.height=h+'px';stage.style.width=w+'px';stage.style.height=h+'px';for(let pass=0;pass<2;pass++){const vw=viewport.clientWidth||available()-2,vh=viewport.clientHeight||maxHeight()-2;surface.style.width=Math.max(vw,w)+'px';surface.style.height=Math.max(vh,h)+'px';stage.style.left=Math.max(0,(vw-w)/2)+'px';stage.style.top=Math.max(0,(vh-h)/2)+'px';}el('totalZoom').value=Math.round(zoom*100);el('zoomLabel').textContent=Math.round(zoom*100)+'%';fields();}
 function syncAttached(){for(const l of layers){if(!l.overlay||!l.parent||overrides.has(l.id))continue;const parent=layers.find(p=>p.id===l.parent);if(!parent)continue;const r=l.relative;l.rect=clampRect({x:parent.rect.x+r.x*parent.rect.w,y:parent.rect.y+r.y*parent.rect.h,w:r.w*parent.rect.w,h:r.h*parent.rect.h},canvas.width,canvas.height);}}
 function draw(){const ctx=canvas.getContext('2d');ctx.fillStyle='#100f18';ctx.fillRect(0,0,canvas.width,canvas.height);for(const l of layers)paint(ctx,l);postprocess?.(canvas);el('sizeHint').textContent='Ảnh tổng '+canvas.width+' × '+canvas.height+' px · Giới hạn 5000 × 5000 px · Viền Xe/Linh tinh theo tùy chọn.';const title=document.getElementById('totalDimensions');if(title)title.textContent='Ảnh tổng · '+canvas.width+' × '+canvas.height+' px';fields();}
 function setZoom(n,anchor){const r=viewport.getBoundingClientRect(),sr=stage.getBoundingClientRect(),cx=anchor?.x??r.left+(viewport.clientLeft||0)+viewport.clientWidth/2,cy=anchor?.y??r.top+(viewport.clientTop||0)+(viewport.clientHeight||400)/2,px=(cx-sr.left)/zoom,py=(cy-sr.top)/zoom;zoom=Math.max(.05,Math.min(4,n));zoomManual=true;layout();const after=viewport.getBoundingClientRect();viewport.scrollLeft=Math.max(0,Math.min(Math.max(0,canvas.width*zoom-viewport.clientWidth),(parseFloat(stage.style.left)||0)+px*zoom-(cx-after.left-(viewport.clientLeft||0))));viewport.scrollTop=Math.max(0,Math.min(Math.max(0,canvas.height*zoom-(viewport.clientHeight||400)),(parseFloat(stage.style.top)||0)+py*zoom-(cy-after.top-(viewport.clientTop||0))));}
 function fit(){zoom=Math.min(1,(available()-3)/canvas.width,(maxHeight()-3)/canvas.height);zoom=Math.max(.05,zoom);zoomManual=false;layout();viewport.scrollLeft=viewport.scrollTop=0;}
 function defaults(w,h,next){return next.map(l=>({...l,rect:clampRect({x:l.rect.x*canvas.width/w,y:l.rect.y*canvas.height/h,w:l.rect.w*canvas.width/w,h:l.rect.h*canvas.height/h},canvas.width,canvas.height)}));}
 function setScene(w,h,next,keepMain=false){if(keepMain&&layers.length){const oldW=canvas.width,oldH=canvas.height,previous=new Map(layers.map(l=>[l.id,l.rect]));next=next.map(l=>{if(previous.has(l.id))return {...l,rect:{...previous.get(l.id)}};const rw=l.rect.w*oldW/w,rh=l.rect.h*oldH/h;return {...l,rect:{x:(oldW-rw)/2,y:(oldH-rh)/2,w:rw,h:rh}};});w=oldW;h=oldH;}base={w,h,layers:next};drag=null;marquee.hidden=true;canvas.width=customSize?.w||w;canvas.height=customSize?.h||h;const original=defaults(w,h,next);if(!validLayout(solids(original)))throw Error('Các khối mặc định bị chồng nhau. Bấm Tự xếp tất cả hoặc kiểm tra bố cục.');layers=original.map(l=>{const p=overrides.get(l.id);return p?{...l,rect:clampRect({x:p.x*canvas.width,y:p.y*canvas.height,w:p.w*canvas.width,h:p.h*canvas.height},canvas.width,canvas.height)}:l;});if(!validLayout(solids(layers))){layers=original;overrides.clear();hint('Nội dung mới làm bố cục chỉnh tay chồng nhau; đã tự xếp lại để giữ các khối riêng biệt.');}syncAttached();selected=new Set([...selected].filter(id=>layers.some(l=>l.id===id)));if(!selected.size&&layers.length)selected.add(layers[0].id);const select=el('blockSelect');select.replaceChildren();const prompt=document.createElement('option');prompt.value='';prompt.textContent='Chọn khối / bôi chọn nhiều';select.append(prompt);for(const l of layers){const op=document.createElement('option');op.value=l.id;op.textContent=l.label||names[l.id]||l.id;select.append(op);}el('totalWidth').value=canvas.width;el('totalHeight').value=canvas.height;el('totalEditor').hidden=!layers.length;draw();if(!zoomManual)fit();else layout();}
 function point(e){const r=stage.getBoundingClientRect();return {x:(e.clientX-r.left)/zoom,y:(e.clientY-r.top)/zoom};}
 function records(){return chosen().map(l=>({id:l.id,rect:{...l.rect}}));}
 function change(target,from=records()){if(!from.length)return;const old=bounds(from.map(l=>l.rect)),r=clampRect(target,canvas.width,canvas.height),end=from.map(l=>({x:r.x+(l.rect.x-old.x)*r.w/old.w,y:r.y+(l.rect.y-old.y)*r.h/old.h,w:l.rect.w*r.w/old.w,h:l.rect.h*r.h/old.h})),ids=new Set(from.map(l=>l.id)),current=from.map(l=>({...layers.find(x=>x.id===l.id).rect})),solidIndices=from.map((l,i)=>layers.find(x=>x.id===l.id).overlay?-1:i).filter(i=>i>=0),others=layers.filter(l=>!ids.has(l.id)&&!l.overlay).map(l=>l.rect),result=constrain(solidIndices.map(i=>current[i]),solidIndices.map(i=>end[i]),others);from.forEach((item,i)=>{const l=layers.find(l=>l.id===item.id);l.rect=Object.fromEntries(['x','y','w','h'].map(k=>[k,current[i][k]+(end[i][k]-current[i][k])*result.t]));save(l);});syncAttached();hint(result.limited?'Đã dừng tại mép khối khác. Thu nhỏ hoặc tạo khoảng trống trước khi kéo tiếp.':from.some(item=>layers.find(l=>l.id===item.id).overlay)?'Ảnh Linh tinh có thể kéo ra ngoài vùng xe và đặt lên vùng khác trong ảnh tổng. Kéo góc để đổi ngang/cao.':'Các khối chính không chồng nhau. Lăn chuột để zoom; Shift + kéo để chọn nhiều.');draw();}
 function setTool(next){tool=next;el('moveTool').classList.toggle('active',tool==='move');el('selectTool').classList.toggle('active',tool==='select');stage.style.cursor=tool==='select'?'crosshair':'move';canvas.style.cursor=stage.style.cursor;}
 stage.onpointerdown=e=>{if(e.button!==undefined&&e.button!==0&&e.button!==1)return;const p=point(e);if(e.button===1){drag={mode:'pan',clientX:e.clientX,clientY:e.clientY,x:viewport.scrollLeft||0,y:viewport.scrollTop||0};}else{const handle=e.target?.dataset?.handle,hit=[...layers].reverse().find(l=>p.x>=l.rect.x&&p.x<=l.rect.x+l.rect.w&&p.y>=l.rect.y&&p.y<=l.rect.y+l.rect.h);if(tool==='select'||e.shiftKey||(!hit&&!handle)){drag={mode:'select',p,previous:new Set(selected),add:!!(e.ctrlKey||e.metaKey)};marquee.hidden=false;}else if(e.ctrlKey||e.metaKey){if(hit){if(selected.has(hit.id))selected.delete(hit.id);else selected.add(hit.id);}fields();return;}else{if(!handle&&hit&&!selected.has(hit.id))selected=new Set([hit.id]);const r=selectedBounds();if(!r)return;drag={mode:handle||'move',p,r,from:records()};}}stage.setPointerCapture(e.pointerId);fields();e.preventDefault?.();};
 stage.onpointermove=e=>{if(!drag)return;if(drag.mode==='pan'){viewport.scrollLeft=drag.x-(e.clientX-drag.clientX);viewport.scrollTop=drag.y-(e.clientY-drag.clientY);return;}const p=point(e);if(drag.mode==='select'){drag.box={x:Math.min(p.x,drag.p.x),y:Math.min(p.y,drag.p.y),w:Math.abs(p.x-drag.p.x),h:Math.abs(p.y-drag.p.y)};Object.assign(marquee.style,{left:drag.box.x*zoom+'px',top:drag.box.y*zoom+'px',width:drag.box.w*zoom+'px',height:drag.box.h*zoom+'px'});return;}const dx=p.x-drag.p.x,dy=p.y-drag.p.y,r=drag.r;let next;if(drag.mode==='move')next={...r,x:r.x+dx,y:r.y+dy};else{let x=r.x,y=r.y,right=r.x+r.w,bottom=r.y+r.h;if(drag.mode.includes('w'))x=Math.max(0,Math.min(right-8,r.x+dx));else right=Math.min(canvas.width,Math.max(x+8,right+dx));if(drag.mode.includes('n'))y=Math.max(0,Math.min(bottom-8,r.y+dy));else bottom=Math.min(canvas.height,Math.max(y+8,bottom+dy));next={x,y,w:right-x,h:bottom-y};}change(next,drag.from);};
 function finish(cancel=false){if(drag?.mode==='select'){selected=cancel?drag.previous:(drag.add?new Set(drag.previous):new Set());if(!cancel&&drag.box)for(const l of layers)if(overlaps(l.rect,drag.box))selected.add(l.id);fields();}drag=null;marquee.hidden=true;}
 stage.onpointerup=()=>finish();stage.onpointercancel=()=>finish(true);
 function deselect(){selected.clear();drag=null;marquee.hidden=true;fields();}
 viewport.onpointerdown=e=>{if((e.button===undefined||e.button===0)&&(e.target===viewport||e.target===surface))deselect();};
 document.addEventListener?.('pointerdown',e=>{if((e.button===undefined||e.button===0)&&!e.target?.closest?.('#totalStage, .total-options'))deselect();});
 viewport.onwheel=e=>{if(!layers.length)return;e.preventDefault();setZoom(zoom*Math.exp(-Math.max(-100,Math.min(100,e.deltaY))*.002),{x:e.clientX,y:e.clientY});};
 el('blockSelect').onchange=()=>{selected=el('blockSelect').value?new Set([el('blockSelect').value]):new Set();fields();};
 el('moveTool').onclick=()=>setTool('move');el('selectTool').onclick=()=>setTool('select');el('selectAllBlocks').onclick=()=>{selected=new Set(layers.map(l=>l.id));fields();};
 el('applyBlock').onclick=()=>{const r={x:Number(el('blockX').value),y:Number(el('blockY').value),w:Number(el('blockW').value),h:Number(el('blockH').value)};if(!Object.values(r).every(Number.isFinite)||r.w<8||r.h<8){hint('Rộng và cao phải từ 8 px, các giá trị phải là số.');return;}change(r);};
 el('resetBlock').onclick=()=>{if(!base)return;const original=defaults(base.w,base.h,base.layers),next=layers.map(l=>selected.has(l.id)?original.find(o=>o.id===l.id):l);if(!validLayout(solids(next))){hint('Vị trí mặc định đang bị khối khác chiếm. Tạo khoảng trống hoặc bấm Tự xếp tất cả.');return;}layers=next;for(const id of selected)overrides.delete(id);syncAttached();draw();};
 el('resetAllBlocks').onclick=()=>{overrides.clear();customSize=null;if(base)setScene(base.w,base.h,base.layers);};
 el('applyTotalSize').onclick=()=>{const w=Number(el('totalWidth').value),h=Number(el('totalHeight').value);if(!Number.isInteger(w)||!Number.isInteger(h)||w<100||h<100||w>5000||h>5000){hint('Kích thước ảnh tổng từ 100 đến 5000 px mỗi chiều.');return;}for(const l of layers)save(l);customSize={w,h};if(base)setScene(base.w,base.h,base.layers);};
 el('totalZoom').oninput=()=>setZoom(Number(el('totalZoom').value)/100);el('zoomIn').onclick=()=>setZoom(zoom*1.25);el('zoomOut').onclick=()=>setZoom(zoom/1.25);el('zoomFit').onclick=fit;root.addEventListener?.('resize',()=>{if(zoomManual)layout();else if(layers.length)fit();});setTool('move');
 return {canvas,setScene,getLayers:()=>layers,getSelection:()=>[...selected],getZoom:()=>zoom,deselect,exportSettings(){return {positions:Object.fromEntries([...overrides].filter(([id])=>names[id])),size:customSize};},applySettings(data,preserveOverlays=false){const transient=preserveOverlays?[...overrides].filter(([id])=>id.startsWith('misc-')):[];overrides.clear();for(const [id,r]of transient)overrides.set(id,r);for(const [id,r]of Object.entries(data?.positions||{}))if(names[id]&&['x','y','w','h'].every(k=>Number.isFinite(r[k]))&&r.w>0&&r.h>0)overrides.set(id,{...r});const size=data?.size;customSize=size&&['w','h'].every(k=>Number.isInteger(size[k])&&size[k]>=100&&size[k]<=5000)?{...size}:null;},resize(id,w,h){const l=layers.find(l=>l.id===id);if(!l)return false;selected=new Set([id]);change({...l.rect,w,h},[{id:l.id,rect:{...l.rect}}]);return true;},select(id){if(!layers.some(l=>l.id===id))return false;selected=new Set([id]);setTool('move');fields();return true;},forget(id){overrides.delete(id);syncAttached();draw();},clear(){layers=[];base=null;overrides.clear();customSize=null;zoomManual=false;selected.clear();drag=null;canvas.width=1;canvas.height=1;el('totalEditor').hidden=true;outline.hidden=true;marquee.hidden=true;el('selectedBoxes').replaceChildren();},draw};
}
root.AccEditor={create,clampRect,overlaps,validLayout,constrain};
})(typeof window!=='undefined'?window:globalThis);
